### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by JLBA** [Huluti/Coulr#2]
Hi,

I'm trying to install Coulr on Ubuntu 14.10 but the installer can't resolve dependancies : 
 coulr : Dépend: qt5-default mais ne sera pas installé (= won't be installed)
         Dépend: qtlocation5-dev mais ne sera pas installé (= wont't be installed)
         Dépend: qtdeclarative5-dev mais ne sera pas installé (=won't be installed)
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

Thanks for you help.

**Comment by Huluti** [comment]
Sorry, I don't want to work with Ubuntu PPA anymore. But I'm currently working on making a debian repo to share my softs and I will take the opportunity to redo the deb packages . When it will be available I will contact you.

**Comment by JLBA** [comment]
Thanks for your answer. I’ll wait for.

JL Test
jltest@free.fr

**Comment by Huluti** [comment]
Hi, first I apologize for the time I took to take care of this software.
I change my mind about using Ubuntu PPA and so I decide to continue using it.
I redid a build for the current version of Ubuntu. On a blank image of Ubuntu, Coulr installs successfully with dependencies. After all this time, can you tell me if you manage to install it?

Thank you in advance and sorry again.
