### ISSUE TITLE
Color picker is a couple pixels off to the horizontal axis

### ISSUE THREAD

**Issue by lepa22** [Huluti/Coulr#26]
The color picker is a couple of pixels off to the horizontal axis. As you can see in the following screenshot, the point of the color picker is clearly in the blue region, however the color picked is yellow, which is a couple pixels to the left:

![image](https://github.com/Huluti/Coulr/assets/16370046/d9d6c577-9301-45c0-9c20-e9ec4c84af2c)

Color picking on the vertical axis seems to work okay.

Additionally, it looks like the color picking point of the cursor is at the white border of it. But is there really a need for the white border? I think that the cursor without it should suffice, as the black point of the cursor is where I would expect the color picking to happen.

**Comment by Huluti** [comment]
I think it's more an issue of [libportal](https://github.com/flatpak/libportal) rather than Coulr.
