### ISSUE TITLE
Perfect. Just one thing. Please add a color picker.

### ISSUE THREAD

**Issue by lb-d** [Huluti/Coulr#7]
That would be so great. Thanks.

**Comment by Huluti** [comment]
Hi! It's on my list since a long time! I It will motivate me to implement it :)

**Comment by lb-d** [comment]
Nice. This could become the best color tool on flathub. :)

**Comment by Huluti** [comment]
@lb-d Hi! could you keep this issue just for the color picker and open a new issue for the save functionality please?
Thank's in advance! I've started to work on the color picker feature.

**Comment by lb-d** [comment]
Sweet. Sure thing. 
Btw. I update flatpaks every day so I'll beta test when a new version comes out and let you know if I find any bugs.

**Comment by Huluti** [comment]
@lb-d took three years but available now in 2.0.0 thanks to @rk234 😎

**Comment by lb-d** [comment]
Hahaha, that's funny :)
The cursor is fantastic. I really like the color preview and the pointed picker for accuracy. Other color pickers fall flat on this. Good job guys :+1:
